// Builds assets/lipsync.js: how open Spark's mouth is on every frame, from the voiceover clips.
//
// Reads the <audio id="vo-…"> clips that tools/voiceover.mjs placed in index.html, decodes each with
// ffmpeg, measures loudness per frame (30 fps), maps it to 0–9 and writes
//   window.EggLipsync = { fps: 30, data: "000013578742…" }   (one character per frame of the episode)
// Scenes then call Egg.lipsync(tl, spark, Egg.sceneStart(id), from, to).
//
// Usage (from the episode folder, after tools/voiceover.mjs):  node tools/lipsync.mjs
// Set FFMPEG to the ffmpeg binary if it isn't on PATH.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const FPS = 30, RATE = 16000;
const FLOOR_DB = -42, RANGE_DB = 26, RELEASE = 0.55; // quiet → closed, loud → open; mouths close a bit slower than they open

const project = join(dirname(fileURLToPath(import.meta.url)), "..");
const index = readFileSync(join(project, "index.html"), "utf8");
const total = +(index.match(/data-composition-id="main"[^>]*?data-duration="([\d.]+)"/) || index.match(/data-duration="([\d.]+)"[^>]*data-composition-id="main"/) || [0, 60])[1];
const frames = new Float32Array(Math.ceil(total * FPS));

const clips = [...index.matchAll(/<audio[^>]*id="vo-[^"]*"[^>]*>/g)].map((m) => ({
  src: m[0].match(/src="([^"]+)"/)[1],
  start: +m[0].match(/data-start="([\d.]+)"/)[1],
  dur: +m[0].match(/data-duration="([\d.]+)"/)[1],
}));
if (!clips.length) throw new Error("No vo-… clips in index.html; run tools/voiceover.mjs first");

const ffmpeg = process.env.FFMPEG || "ffmpeg";
for (const c of clips) {
  const pcm = execFileSync(ffmpeg, ["-v", "error", "-i", join(project, c.src), "-f", "s16le", "-ac", "1", "-ar", String(RATE), "-"], { maxBuffer: 1 << 28 });
  const samples = new Int16Array(pcm.buffer, pcm.byteOffset, Math.floor(pcm.length / 2));
  const per = RATE / FPS;
  let prev = 0;
  for (let f = 0; f * per < samples.length && f / FPS < c.dur; f++) {
    let sum = 0;
    const a = Math.floor(f * per), b = Math.min(samples.length, Math.floor((f + 1) * per));
    for (let i = a; i < b; i++) sum += (samples[i] / 32768) ** 2;
    const db = 10 * Math.log10(sum / Math.max(1, b - a) + 1e-10);
    const raw = Math.min(1, Math.max(0, (db - FLOOR_DB) / RANGE_DB));
    const v = Math.max(raw, prev * RELEASE);
    prev = v;
    const g = Math.round((c.start * FPS) + f);
    if (g >= 0 && g < frames.length) frames[g] = Math.max(frames[g], v);
  }
}

const data = Array.from(frames, (v) => String.fromCharCode(48 + Math.round(v * 9))).join("");
writeFileSync(join(project, "assets", "lipsync.js"), `// Generated by tools/lipsync.mjs from the voiceover. Do not edit.\nwindow.EggLipsync = { fps: ${FPS}, data: "${data}" };\n`);
const talking = data.split("").filter((ch) => ch > "1").length;
console.log(`${clips.length} clips → ${frames.length} frames (${(talking / FPS).toFixed(1)}s of mouth movement) → assets/lipsync.js`);
