// Collects each scene's sound cues and writes them into index.html as <audio> clips at episode time.
//
// A scene declares its cues in <head> (outside <template>, so the runtime ignores it):
//   <script type="application/json" class="sfx-cues">[{"t":0.3,"sfx":"pop","vol":0.35}]</script>
// t = seconds from the scene's start, sfx = file name in assets/sfx (no extension),
// vol = 0..1 (default 0.3), dur = optional trim in seconds.
//
// Usage (from the project folder):  node tools/build-sfx.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const project = join(dirname(fileURLToPath(import.meta.url)), "..");
const indexPath = join(project, "index.html");
let index = readFileSync(indexPath, "utf8");

// Seconds, from the bundled library manifest.
const LENGTH = {
  chime: 2.5, "click-soft": 0.37, click: 0.37, error: 1.62, "impact-bass-1": 2.12, "key-press": 0.4,
  ping: 1.32, pop: 0.72, sparkle: 1.8, typing: 1.5, "whoosh-short": 0.57, whoosh: 0.57,
};
const FIRST_TRACK = 10;

const hosts = [...index.matchAll(/<div[^>]*data-composition-src="([^"]+)"[^>]*>/g)].map((m) => {
  const start = +(m[0].match(/data-start="([\d.]+)"/) || [0, 0])[1];
  const id = (m[0].match(/data-composition-id="([^"]+)"/) || [0, "scene"])[1];
  return { src: m[1], start, id };
});

const cues = [];
for (const h of hosts) {
  const file = join(project, h.src);
  if (!existsSync(file)) continue;
  const m = readFileSync(file, "utf8").match(/<script type="application\/json" class="sfx-cues">([\s\S]*?)<\/script>/);
  if (!m) continue;
  JSON.parse(m[1]).forEach((c, i) => {
    const file = `assets/sfx/${c.sfx}.mp3`;
    if (!existsSync(join(project, file))) throw new Error(`${h.src}: missing ${file}`);
    const dur = Math.min(c.dur ?? LENGTH[c.sfx] ?? 1, LENGTH[c.sfx] ?? 99);
    cues.push({ id: `sfx-${h.id}-${i + 1}`, file, start: +(h.start + c.t).toFixed(3), dur: +dur.toFixed(3), vol: c.vol ?? 0.3 });
  });
}

// Greedy track assignment so no two clips overlap on one track.
cues.sort((a, b) => a.start - b.start);
const trackEnds = [];
for (const c of cues) {
  let k = trackEnds.findIndex((end) => end <= c.start);
  if (k === -1) { k = trackEnds.length; trackEnds.push(0); }
  trackEnds[k] = c.start + c.dur + 0.01;
  c.track = FIRST_TRACK + k;
}

const tags = cues
  .map((c) => `      <audio id="${c.id}" src="${c.file}" data-start="${c.start}" data-duration="${c.dur}" data-track-index="${c.track}" data-volume="${c.vol}"></audio>`)
  .join("\n");
const block = `<!-- sfx:start (generated by tools/build-sfx.mjs; edit the cues in each scene, then rerun) -->\n${tags}\n      <!-- sfx:end -->`;
if (!/<!-- sfx:start[\s\S]*?<!-- sfx:end -->/.test(index)) throw new Error("index.html needs <!-- sfx:start --> and <!-- sfx:end --> markers inside the root");
index = index.replace(/<!-- sfx:start[\s\S]*?<!-- sfx:end -->/, block);
writeFileSync(indexPath, index);
console.log(`${cues.length} cues on ${trackEnds.length} tracks from ${hosts.length} scenes`);
